Работа с Map!)
EBogatyreva/sky-pro-work-with-exceptions pull request #4
Opened 2022-04-06 11:08 UTC by EBogatyreva

2022-04-06 21:08 UTC, rmuhamedgaliev requested changes
Требуются правки

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
>          String a = null;
Что такое a?

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
> +    Map<Integer, Employee> employees;
Переменную надо защищать. Повторяем тему инкапсуляции

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
> +    public String addNewEmployee(Integer index, String firstName, String lastName) throws BadRequest {
Тут ничего меняться в аргументах не должно, принимаем имя и фамилию, но на выходе возвращаем уже объект сотрудника. Индексы система должна генерировать сама, без клиента. 

Подумай что еще можно использовать как ключ вместо Integer и учесть условие

> чтобы сотрудник с одним ФИО существовал только в одном экземпляре

Ты должна мочь искать сотрудника по ФИО, без индекса, а если хочешь индексы, то добавь внутрь сотрудника, но оно не трубеутся в этом задании.

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
> +    public String delEmployee(Integer index, String firstName, String lastName) throws NotFoundException {
Забываем про индекс, у нас только ФИО есть.

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
> +    public String findEmployee(Integer index, String firstName, String lastName) throws NotFoundException {
Забываем про индекс, у нас только ФИО есть.

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
>          String a1 = null;
Что такое a1?

2022-04-06 21:08 UTC, rmuhamedgaliev commented on src/main/java/pro/sky/skyproworkwithexceptions/service/EmployeeService.java
>      boolean equals(Object obj);
Для чего служит эта функция?

2022-04-08 10:09 UTC, EBogatyreva commented on src/main/java/pro/sky/skyproworkwithexceptions/service/EmployeeService.java
>      boolean equals(Object obj);
я в доработанной версии убрала ее)) это с прошлого урока) простите не увидела)!

2022-04-08 10:12 UTC, EBogatyreva commented on src/main/java/pro/sky/skyproworkwithexceptions/service/impl/EmployeeServiceImpl.java
>          String a1 = null;
это тоже с прошлого урока) 
убрала)

2022-04-08 19:08 UTC, rmuhamedgaliev approved these changes
Принято

2022-04-08 22:23 UTC, merged